server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/usawentao/ConfigServer # \u6307\u5B9Agit\u4ED3\u5E93\u5730\u5740
          searchPaths: Cloud # \u6307\u5B9A\u5B50\u6587\u4EF6
          username: # \u6307\u5B9A\u767B\u5F55\u7528\u6237\u540D\u79F0\uFF08\u82E5\u662F\u516C\u5F00\u4ED3\u5E93\u53EF\u4EE5\u4E0D\u586B\uFF09
          password: # \u6307\u5B9A\u767B\u5F55\u5BC6\u7801\uFF08\u82E5\u662F\u516C\u5F00\u4ED3\u5E93\u53EF\u4EE5\u4E0D\u586B\uFF09
      label: master # \u6307\u5B9A\u5206\u652F
eureka:
  instance:
    prefer-ip-address: true # \u4EE5\u672C\u673A\u5B9E\u9645\u5730\u5740\u8FDB\u884C\u6CE8\u518C
  client:
    service-url:
      defaultZone: http://localhost:8889/eureka/