server:
  port: 8769
spring:
  application:
    name: service-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
zuul:
  routes:
    api-a:
      path: /api-a/**  # \u4EE5/api-a/ \u5F00\u5934\u7684\u8BF7\u6C42\u90FD\u8F6C\u53D1\u7ED9service-ribbon\u670D\u52A1
      serviceId: service-ribbon
    api-b:
      path: /api-b/**  # \u4EE5/api-b/\u5F00\u5934\u7684\u8BF7\u6C42\u90FD\u8F6C\u53D1\u7ED9service-feign\u670D\u52A1
      serviceId: service-feign
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
ribbon: # 添加ribbon的超时时间设置
  ReadTimeout: 3000
  ConnectTimeout: 3000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 3000