#匹配请求Header头中Cookie中name为Edward时放行。 验证：curl -H 'Cookie:name=Edward' localhost:8081
spring:
  cloud:
    gateway:
      routes:
      - id: cookie_route
        uri: http://httpbin.org:80/get
        predicates:
        - Cookie=name,Edward